version: "2"

services:
  booksonic:
    image: linuxserver/booksonic
    container_name: booksonic
    environment:
      - PUID=1001
      - PGID=1001
      - TZ=America/Argentina/Buenos_Aires
    volumes:
      - ./booksonic:/config
      - ${MEDIA}/Audiolibros:/audiobooks
      - ${MEDIA}/Podcasts:/podcasts
    ports:
      - 4040:4040
    restart: unless-stopped

  samba:
    image: dperson/samba:rpi
    restart: always
    command: '-u "pi;password" -s "media;/media;yes;no" -s "downloads;/downloads;yes;no"'
    stdin_open: true
    tty: true
    ports:
      - 139:139
      - 445:445
    volumes:
      - /usr/share/zoneinfo/America/Argentina/Buenos_Aires:/etc/localtime
      - ${MEDIA}:/media
      - ${STORAGE}/torrents:/downloads

  plex:
    image: jaymoulin/plex:1.16.5
    expose:
      - 32400
      - 33400
    hostname: raspberrypi
    volumes:
      - ${STORAGE}/Plex Media Server:/root/Library/Application Support/Plex Media Server
      - ${MEDIA}:/media
      - ${STORAGE}/tmp:/tmp
    restart: unless-stopped
    networks:
      lan:
        ipv4_address: 192.168.0.3

  transmission:
    image: linuxserver/transmission
    container_name: transmission
    environment:
      - PUID=1001
      - PGID=1001
      - TRANSMISSION_WEB_HOME=/transmission-web-control/
    volumes:
      - ./transmission:/config
      - ${STORAGE}/torrents:/downloads
    ports:
      - 9091:9091
      - 51413:51413
      - 51413:51413/udp
    restart: unless-stopped

  flexget:
    image: wiserain/flexget
    volumes:
      - ./flexget:/config
      - ${STORAGE}/torrents:/data
      - ${MEDIA}:/storage
      - ${STORAGE}/tmp:/stor_temp
    ports:
      - 5050:5050
    environment:
      - TORRENT_PLUGIN=transmission
      - TZ=America/Argentina/Buenos_Aires
      - FG_WEBUI_PASSWD=trans123456
      - FG_LOG_LEVEL=info
      - PUID=1001
      - PGID=1001
    restart: unless-stopped
    links:
      - transmission

  duckdns:
    image: linuxserver/duckdns
    container_name: duckdns
    environment:
      - TZ=America/Argentina/Buenos_Aires
      - SUBDOMAINS=depcordoba
      - TOKEN=${DUCKDNS_TOKEN}
      - LOG_FILE=false
    restart: always



networks:
  lan:
    driver: macvlan
    driver_opts:
      parent: eth0
    ipam:
      config:
        - subnet: "192.168.0.0/24"
          gateway: "192.168.0.1"
